# -*- coding: utf-8 -*-
"""summarizeX_ar2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vLZltWZpVtsbxnwaocN6wuRBk29GhGe2
"""


from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

# Load the BART model and tokenizer
model_name = "facebook/bart-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

# Provide the input Arabic text

def run_arabic_summary(reviews):
    input_text = ".".join(reviews)
    # Preprocess and tokenize the input text
    inputs = tokenizer.encode(input_text, return_tensors="pt", max_length=1024, truncation=True)

    # Generate the summary
    summary_ids = model.generate(inputs, max_length=150, num_beams=4, early_stopping=True)
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

    # Print the summary
    print("Summary:", summary)

    return summary

